extends Node

var parts: Dictionary = {
	"Placeholder Head": [0, 0, 0, "Glorf", load("res://Assets/Parts/PLACEHOLDER/h110-0420.png")],
	"Basic Head": [0, 1, 0, "The head you started off with"],
	"Basic Torso": [0, 1, 0, "The torso you started off with"],
	"Basic Left Arm": [1, 0, 0, "The left arm you started off with"],
	"Basic Right Arm": [1, 0, 0, "The right arm you started off with"],
	"Basic Left Leg": [0, 0, 1, "The left leg you started off with"],
	"Basic Right Leg": [0, 0, 1, "The right leg you started off with"],
	"Tank Head": [0, 3, 0, "Head taken from tank enemy. The rough material boosts your defence"],
	"Tank Torso": [0, 2, -1, "Torso taken from tank enemy. The rough material boosts your defence, but the part is quite heavy"] ,
	"Tank Left Arm": [2, 2, -1, "Left arm taken from tank enemy. The rough plating on the knuckles boosts your attack, but is quite heavy"] ,
	"Tank Right Arm": [2, 2, -1, "Right arm taken from tank enemy. The rough plating on the knuckles boosts your attack, but is quite heavy"],
	"Tank Left Leg": [0, 0, 0, "Left leg taken from tank enemy"],
	"Tank Right Leg": [0, 0, 0, "Right leg taken from tank enemy"],
	"Bull Head": [2, -2, 0, "Head taken from bull enemy. The horns increase your attack and allow you to burst through terrain at the cost of some defence"],
	"Bull Torso": [0, 0, 1, "Torso taken from bull enemy. Because it's lighter than a normal torso, you can move faster if you have it equiped"],
	"Bull Left Arm": [2, 0, 0, "Left arm taken from bull enemy. The plating on the knuckles is harder than on the tank enemy, and stretches all the way down the fingers"],
	"Bull Right Arm": [2, 0, 0, "Right arm taken from bull enemy. The plating on the knuckles is harder than on the tank enemy, and sretches all the way down the fingers"],
	"Bull Left Leg": [0, 0, 2, "Left leg taken from bull enemy. The thick and strong structure pushes towards the ground with greater power, increasing your speed"],
	"Bull Right Leg": [0, 0, 2, "Right leg taken from bull enemy. The thick and strong structure pushes towards the ground with greater power, increasing your speed"],
	"Scavenger Head": [0, 0, 1, "Head taken from scavenger enemy. When equipped, you will recieve weak signals from interest points on the map"],
	"Scavenger Torso": [0, 0, 1, "Torso taken from scavenger enemy. The light weight not only allows you to move faster, but to jump higher"],
	"Scavenger Left Arm": [1, 0, 0, "Left arm taken from scavenger enemy. The flimsy claws provide a weak form of attack"],
	"Scavenger Right Arm": [1, 0, 0, "Right arm taken from scavenger enemy. The flimsy claws provide a weak form of attack"],
	"Scavenger Left Leg": [0, 0, 1, "Left leg taken from scavenger enemy. The specific form of the feet allow for faster movement"],
	"Scavenger Right Leg": [0, 0, 1, "Right leg taken from scavenger enemy. The specific form of the feet allow for faster movement"],
	"Blaster Head": [0, 1, 0, "Head taken from blaster enemy. The healmet like shape reduces damage from ranged attacks"],
	"Blaster Torso": [0, 1, -1, "Torso taken from blaster enemy. The heavy machinery provides protection against attacks"],
	"Blaster Left Arm": [2, 0, -1, "Left arm taken from blaster enemy. The acid gun module is attatched, providing an excellent weapon that also deals poison damage"],
	"Blaster Right Arm": [2, 0, -1, "Right arm taken from blaster enemy. The grenade launcher attatched deals huge damage in a big range, but deals recoil on the user"],
	"Blaster Left Leg": [0, 0, -1, "Left leg taken from blaster enemy. The short stubby structure limits your speed"],
	"Blaster Right Leg": [0, 0, -1, "Right leg taken from blaster enemy. The short stubby structure limits your speed"],
	"Damaged Jetpack": [0, 0, 0, "Jetpack scavenged from dead body. Propulses you in the air and allows you to glide, but due to the damage flight is not attainable"],
	"Hacking Module": [0, 0, 0, "A high tech module able to temporarily hack into enemy systems and giving access to their data"],
	"EMP Grenade": [0, 0, 0, "EMP grenade scavenged from dead body. Has a one time bomb attatched that disrupts all robotic enemies in a given radius"],
	"Remote Drone": [0, 0, 0, "A gun with what seems like an egg shaped bullet. Inside is a small spider-like drone you can use to explore unreachable areas."]
	}
